language: node_js
node_js:
  - "0.12"
services:
  - mongodb
addons:
  code_climate:
    repo_token: 9573d64ceb6d872605a6168709fad95cbe4664cc8b7c2f2e3fbad19975e38d84
after_script:
	- codeclimate-test-reporter < lcov.info